In [4]:
import sqlite3
import pandas as pd
import sys
from pathlib import Path

ROOT = Path("../").resolve()
sys.path.append(str(ROOT))
from src.analytics.cagr import compute_metric_cagr

conn = sqlite3.connect("../data/nifty100.db")

pl = pd.read_sql("""
SELECT
    company_id,
    year,
    sales,
    net_profit,
    eps
FROM profitandloss
""", conn)

conn.close()

pl = compute_metric_cagr(pl, "sales", 3)
pl = compute_metric_cagr(pl, "sales", 5)
pl = compute_metric_cagr(pl, "sales", 10)

pl = compute_metric_cagr(pl, "net_profit", 3)
pl = compute_metric_cagr(pl, "net_profit", 5)
pl = compute_metric_cagr(pl, "net_profit", 10)

pl = compute_metric_cagr(pl, "eps", 3)
pl = compute_metric_cagr(pl, "eps", 5)
pl = compute_metric_cagr(pl, "eps", 10)

pl.head()

,company_id,year,sales,net_profit,eps,sales_cagr_3yr,sales_flag_3yr,sales_cagr_5yr,sales_flag_5yr,sales_cagr_10yr,...,net_profit_cagr_5yr,net_profit_flag_5yr,net_profit_cagr_10yr,net_profit_flag_10yr,eps_cagr_3yr,eps_flag_3yr,eps_cagr_5yr,eps_flag_5yr,eps_cagr_10yr,eps_flag_10yr
0,ABB,2012-12,1653.0,145.0,68.0,NaN,INSUFFICIENT,NaN,INSUFFICIENT,NaN,...,NaN,INSUFFICIENT,NaN,INSUFFICIENT,NaN,INSUFFICIENT,NaN,INSUFFICIENT,NaN,INSUFFICIENT
1,ABB,2014-03,2276.0,198.0,93.0,NaN,INSUFFICIENT,NaN,INSUFFICIENT,NaN,...,NaN,INSUFFICIENT,NaN,INSUFFICIENT,NaN,INSUFFICIENT,NaN,INSUFFICIENT,NaN,INSUFFICIENT
2,ABB,2015-03,2289.0,229.0,108.0,NaN,INSUFFICIENT,NaN,INSUFFICIENT,NaN,...,NaN,INSUFFICIENT,NaN,INSUFFICIENT,NaN,INSUFFICIENT,NaN,INSUFFICIENT,NaN,INSUFFICIENT
3,ABB,2016-03,2614.0,255.0,120.0,16.5,OK,NaN,INSUFFICIENT,NaN,...,NaN,INSUFFICIENT,NaN,INSUFFICIENT,20.84,OK,NaN,INSUFFICIENT,NaN,INSUFFICIENT
4,ABB,2017-03,2903.0,277.0,130.0,8.45,OK,NaN,INSUFFICIENT,NaN,...,NaN,INSUFFICIENT,NaN,INSUFFICIENT,11.81,OK,NaN,INSUFFICIENT,NaN,INSUFFICIENT

1. Load the data

In [6]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../data/nifty100.db")

pl = pd.read_sql("""
SELECT
    company_id,
    year,
    sales,
    net_profit,
    eps
FROM profitandloss
""", conn)

conn.close()

2. Compute Revenue CAGR

In [7]:
pl = compute_metric_cagr(pl, "sales", 3)

pl[
    [
        "company_id",
        "year",
        "sales",
        "sales_cagr_3yr",
        "sales_flag_3yr"
    ]
].head(15)

    company_id     year   sales sales_cagr_3yr sales_flag_3yr
0          ABB  2012-12  1653.0            NaN   INSUFFICIENT
1          ABB  2014-03  2276.0            NaN   INSUFFICIENT
2          ABB  2015-03  2289.0            NaN   INSUFFICIENT
3          ABB  2016-03  2614.0           16.5             OK
4          ABB  2017-03  2903.0           8.45             OK
5          ABB  2018-03  3298.0          12.95             OK
6          ABB  2019-03  3679.0          12.07             OK
7          ABB  2020-03  4093.0          12.13             OK
8          ABB  2021-03  4310.0           9.33             OK
9          ABB  2022-03  4913.0          10.12             OK
10         ABB  2023-03  5349.0           9.33             OK
11         ABB  2024-03  5849.0          10.71             OK
12         ABB      TTM  6066.0           7.28             OK
13  ADANIENSOL  2014-03     0.0            NaN   INSUFFICIENT
14  ADANIENSOL  2015-03   131.0            NaN   INSUFFICIENT

3. Compute PAT CAGR

In [8]:
pl = compute_metric_cagr(pl, "net_profit", 3)

pl[
    [
        "company_id",
        "year",
        "net_profit",
        "net_profit_cagr_3yr",
        "net_profit_flag_3yr"
    ]
].head(15)

    company_id     year  net_profit net_profit_cagr_3yr net_profit_flag_3yr
0          ABB  2012-12       145.0                 NaN        INSUFFICIENT
1          ABB  2014-03       198.0                 NaN        INSUFFICIENT
2          ABB  2015-03       229.0                 NaN        INSUFFICIENT
3          ABB  2016-03       255.0                20.7                  OK
4          ABB  2017-03       277.0               11.84                  OK
5          ABB  2018-03       401.0               20.53                  OK
6          ABB  2019-03       450.0               20.84                  OK
7          ABB  2020-03       593.0               28.88                  OK
8          ABB  2021-03       691.0               19.89                  OK
9          ABB  2022-03       799.0               21.09                  OK
10         ABB  2023-03       949.0               16.97                  OK
11         ABB  2024-03      1201.0               20.23                  OK
12         ABB      TTM      1285.0               17.16                  OK
13  ADANIENSOL  2014-03         0.0                 NaN        INSUFFICIENT
14  ADANIENSOL  2015-03        -7.0                 NaN        INSUFFICIENT

4. Compute EPS CAGR

In [9]:
pl = compute_metric_cagr(pl, "eps", 3)

pl[
    [
        "company_id",
        "year",
        "eps",
        "eps_cagr_3yr",
        "eps_flag_3yr"
    ]
].head(15)

    company_id     year    eps eps_cagr_3yr  eps_flag_3yr
0          ABB  2012-12   68.0          NaN  INSUFFICIENT
1          ABB  2014-03   93.0          NaN  INSUFFICIENT
2          ABB  2015-03  108.0          NaN  INSUFFICIENT
3          ABB  2016-03  120.0        20.84            OK
4          ABB  2017-03  130.0        11.81            OK
5          ABB  2018-03  189.0        20.51            OK
6          ABB  2019-03  212.0        20.89            OK
7          ABB  2020-03  279.0        28.99            OK
8          ABB  2021-03  325.0         19.8            OK
9          ABB  2022-03  376.0        21.05            OK
10         ABB  2023-03  447.0        17.01            OK
11         ABB  2024-03  565.0        20.24            OK
12         ABB      TTM  605.0        17.18            OK
13  ADANIENSOL  2014-03    0.0          NaN  INSUFFICIENT
14  ADANIENSOL  2015-03    0.0          NaN  INSUFFICIENT

5. Check turnaround flags

In [10]:
pl[
    pl["sales_flag_3yr"] == "TURNAROUND"
]

Empty DataFrame
Columns: [company_id, year, sales, net_profit, eps, sales_cagr_3yr, sales_flag_3yr, net_profit_cagr_3yr, net_profit_flag_3yr, eps_cagr_3yr, eps_flag_3yr]
Index: []

In [11]:
pl["sales_flag_3yr"].value_counts(dropna=False)

sales_flag_3yr
OK              887
INSUFFICIENT    276
ZERO_BASE         1
Name: count, dtype: int64

In [12]:
# Revenue
pl = compute_metric_cagr(pl, "sales", 5)
pl = compute_metric_cagr(pl, "sales", 10)

# PAT
pl = compute_metric_cagr(pl, "net_profit", 3)
pl = compute_metric_cagr(pl, "net_profit", 5)
pl = compute_metric_cagr(pl, "net_profit", 10)

# EPS
pl = compute_metric_cagr(pl, "eps", 3)
pl = compute_metric_cagr(pl, "eps", 5)
pl = compute_metric_cagr(pl, "eps", 10)

In [16]:
pl[
    [
        "company_id",
        "year",
        "sales_cagr_5yr",
        "sales_cagr_10yr",
        "net_profit_cagr_5yr",
        "eps_cagr_10yr"
    ]
].head()

,company_id,year,sales_cagr_5yr,sales_cagr_10yr,net_profit_cagr_5yr,eps_cagr_10yr
0,ABB,2012-12,NaN,NaN,NaN,NaN
1,ABB,2014-03,NaN,NaN,NaN,NaN
2,ABB,2015-03,NaN,NaN,NaN,NaN
3,ABB,2016-03,NaN,NaN,NaN,NaN
4,ABB,2017-03,NaN,NaN,NaN,NaN

In [17]:
for period in [3, 5, 10]:
    print(f"\nSales {period}Y")
    print(pl[f"sales_flag_{period}yr"].value_counts(dropna=False))

Sales 3Y
sales_flag_3yr
OK              887
INSUFFICIENT    276
ZERO_BASE         1
Name: count, dtype: int64

Sales 5Y
sales_flag_5yr
OK              705
INSUFFICIENT    458
ZERO_BASE         1
Name: count, dtype: int64

Sales 10Y
sales_flag_10yr
INSUFFICIENT    907
OK              256
ZERO_BASE         1
Name: count, dtype: int64

In [18]:
for metric in ["net_profit", "eps"]:
    for period in [3, 5, 10]:
        print(f"\n{metric.upper()} {period}Y")
        print(pl[f"{metric}_flag_{period}yr"].value_counts(dropna=False))

NET_PROFIT 3Y
net_profit_flag_3yr
OK                 796
INSUFFICIENT       276
TURNAROUND          43
DECLINE_TO_LOSS     35
BOTH_NEGATIVE       13
ZERO_BASE            1
Name: count, dtype: int64

NET_PROFIT 5Y
net_profit_flag_5yr
OK                 629
INSUFFICIENT       458
TURNAROUND          43
DECLINE_TO_LOSS     27
BOTH_NEGATIVE        6
ZERO_BASE            1
Name: count, dtype: int64

NET_PROFIT 10Y
net_profit_flag_10yr
INSUFFICIENT       907
OK                 241
TURNAROUND          10
DECLINE_TO_LOSS      5
ZERO_BASE            1
Name: count, dtype: int64

EPS 3Y
eps_flag_3yr
OK                 795
INSUFFICIENT       276
TURNAROUND          37
DECLINE_TO_LOSS     32
BOTH_NEGATIVE       11
ZERO_BASE            9
MISSING              4
Name: count, dtype: int64

EPS 5Y
eps_flag_5yr
OK                 625
INSUFFICIENT       458
TURNAROUND          37
DECLINE_TO_LOSS     27
ZERO_BASE            9
BOTH_NEGATIVE        5
MISSING              3
Name: count, dtype: int64

EPS 10Y
eps_flag_10yr
INSUFFICIENT       907
OK                 239
TURNAROUND           9
DECLINE_TO_LOSS      5
ZERO_BASE            3
MISSING              1
Name: count, dtype: int64